const { contextBridge, ipcRenderer } = require('electron');
const wt = require('./core/worktime');

contextBridge.exposeInMainWorld('fairy', {
  getState: () => ipcRenderer.invoke('state:get'),
  getBootTime: () => ipcRenderer.invoke('boot:get'),
  setWorkType: (type, flexMinutes) => ipcRenderer.invoke('day:setWorkType', type, flexMinutes),
  setStart: (mode, manualMs) => ipcRenderer.invoke('day:setStart', mode, manualMs),
  respondAlert: (choice) => ipcRenderer.invoke('alert:respond', choice),
  resume: () => ipcRenderer.invoke('day:resume'),
  getTodos: () => ipcRenderer.invoke('todos:get'),
  addTodo: (text) => ipcRenderer.invoke('todos:add', text),
  toggleTodo: (id) => ipcRenderer.invoke('todos:toggle', id),
  removeTodo: (id) => ipcRenderer.invoke('todos:remove', id),
  carryTodos: (carry) => ipcRenderer.invoke('todos:carry', carry),
  respondNudge: (choice) => ipcRenderer.invoke('nudge:respond', choice),
  setNudgeFreq: (freq) => ipcRenderer.invoke('nudge:setFreq', freq),
  turnOnNudge: () => ipcRenderer.invoke('nudge:turnOn'),
  getPrefs: () => ipcRenderer.invoke('prefs:get'),
  setPrefs: (partial) => ipcRenderer.invoke('prefs:set', partial),
  onPrefs: (cb) => ipcRenderer.on('prefs:changed', (_e, prefs) => cb(prefs)),
  getClockJump: () => ipcRenderer.invoke('clock:get'),
  respondClock: (recalc) => ipcRenderer.invoke('clock:respond', recalc),
  onClockJump: (cb) => ipcRenderer.on('clock:jump', (_e, jump) => cb(jump)),
  onTodos: (cb) => ipcRenderer.on('todos:changed', (_e, todos) => cb(todos)),
  onState: (cb) => ipcRenderer.on('state:changed', (_e, day) => cb(day)),
  onCursor: (cb) => ipcRenderer.on('cursor', (_e, p) => cb(p)),
  openSettings: () => ipcRenderer.send('settings:open'),
  fitSettings: (height) => ipcRenderer.send('settings:fit', height),
  focusWidget: () => ipcRenderer.send('fairy:focus'),
  ignoreMouse: (ignore) => ipcRenderer.send('mouse:ignore', ignore),
  dragStart: () => ipcRenderer.send('drag:start'),
  dragEnd: () => ipcRenderer.send('drag:end'),
});

contextBridge.exposeInMainWorld('wt', {
  WORK_TYPES: wt.WORK_TYPES,
  START_MODES: wt.START_MODES,
  endTime: wt.endTime,
  remaining: wt.remaining,
  alertDue: wt.alertDue,
  elapsed: wt.elapsed,
  formatClock: wt.formatClock,
  formatDuration: wt.formatDuration,
  timeOnDay: wt.timeOnDay,
});
